name: Create PR test

on:
  push:
    branches:
      - master

jobs:

  create-pr:

    continue-on-error: true

    runs-on: windows-latest

    steps:

      - uses: actions/checkout@v2

      - name: Update file
        run: |
          date >> updates.txt

      - name: Check updated
        id: check-updated
        run: |
          git diff
          echo "set-output name=stat::$(git diff --quiet && echo 'clean' || echo 'dirty')"
          echo "foo"
          echo "::set-output name=stat::$(git diff --quiet && echo 'clean' || echo 'dirty')"
          echo "bar"

      - run: |
          echo "foo"

      - run: |
          echo "foo"
          true

      - run: |
          echo "foo"
          $true

      - run: |
          echo "set-output name=stat::$(git diff --quiet && echo 'clean' || echo 'dirty')"
          echo "foo"
          echo "::set-output name=stat::$(git diff --quiet && echo 'clean' || echo 'dirty')"
          echo "bar"
          $true
